### ISSUE TITLE
zmiana biblioteki na npoi, naprawa agendy

### ISSUE THREAD

**Issue by jacekfrackiewicz** [ZespolNumerJeden/zn1Web#22]
Azure nie obsługuje plików excel, zamiana na inny który będzie obsługiwał, csv?

**Comment by jacekfrackiewicz** [comment]
wykorzystanie innej biblioteki?

**Comment by jacekfrackiewicz** [comment]
wgrałem npoi powinno zadziałać:D

**Comment by ArkadioG** [comment]
fixed by #24
