### ISSUE TITLE
Day time to string conversion

### ISSUE THREAD

**Issue by krawan13** [ZespolNumerJeden/zn1Web#36]
data wykrycia : 02/11/2017, 09:00

OPIS
1 otwórz w przeglądarce stronę http://ogarnij-agile.azurewebsites.net/Home/Agenda lub 
2 w aplikacji mobilnej ze skanerem wejdź w Agendę

OCZEKIWANE DZIAŁANIE
prawidłowe konwersja daty na stringa.

AKTUALNE DZIAŁANIE
nie prawidłowe formaty daty:

Dzień: zn1Web.Utils.AgendaClass?.DayTime.ToString("dd MMMM yyyy")  

UWAGI
być może błąd występuje z powodu braku danych.

**Comment by krawan13** [comment]
![skaner app.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d87b61cab1b50012ab1e4f/125516c66e82c728ace21e0d46fb9f9b2d8791e98ef9af01e81fe086264c22703d46f96925dce77be7122e040b5e4ea515595f44fef1897da2be6e76984019af80330b2b9b645bf9fa9015ad00bd2a8a4a85bfba8b4cc1ee3923ef899d02.png)
![web.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d87b61cab1b50012ab1e4f/125516c66e82c728ace21e0d46ff919861cec1b99de6b546a749b2ce6b137e777a5cf37e7581b278e6462a515f5d46ac175c5716faeb9539e4e76224d50152a7842f4d7ed43c16a6b9871fb607bb208a4980b4be825e8d.jpg)

**Comment by ArkadioG** [comment]
ok, mój bład, spowodowane przez null check w wywołaniu

**Comment by krawan13** [comment]
poprawione, sprawdzone, zamykam
