### ISSUE TITLE
Implementacja diagramów ERD

### ISSUE THREAD

**Issue by jacekfrackiewicz** [ZespolNumerJeden/zn1Web#4]

**Comment by ghost** [comment]
Odznaczam @krawan13, bo jest testerem. Tu miał być chyba @KotekMrau (o ile to jest Mateusz Koseda). @Bllazze też przeniesiony do testów, bo się nie aktywizuje.

**Comment by KotekMrau** [comment]
Bllazze czyli jak mniemam Błażej deklarował się i miał to zaimplementować. Dlatego dodaje go z powrotem.

**Comment by ghost** [comment]
@KotekMrau @Bllazze To się panowie skontaktujcie ze sobą.

**Comment by ArkadioG** [comment]
@Bllazze zaimplementuj te diagramy: [https://trello.com/c/adVwIDBh](https://trello.com/c/adVwIDBh )

**Comment by ArkadioG** [comment]
#18
